### PR TITLE
Breakdown the Pomodoro timer into MVC pattern

### PR DESCRIPTION
**Pull request by zhuboyu1**
First try to break down the PomodoroActivity into Pomodoro model and Pomodoro Controller, which follows the MVC pattern

### CODE REVIEW

**Comment by VictoriaXie** [comment]
I think this divison works and it does follow the MVC pattern, but maybe you can also try to put the countdown timer into the pomodoro model class. 
Also, if the github doesn't allow you to merge I think you can solve the conflict locally and push it directly to the master branch.

**Comment by VictoriaXie** [comment]
I think this division works and it does follow the MVC pattern, but maybe you can also try to put the countdown timer into the pomodoro model class.
In addition, if the github doesn't allow you to merge I think you can solve the conflict locally and push it directly to the master branch.

**Comment by zhuboyu1** [comment]
Thank you Victoria, I'll try to change the model part and push it into the master branch!

**Comment by VictoriaXie** [comment]
That sounds good!👍

**Pull request closed without merging**
